language: r
dist: xenial
cran: https://demo.rstudiopm.com/cran/__linux__/xenial/latest

after_success:
  - Rscript -e 'covr::codecov()'
  
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
